// <auto-generated />
using Cocojambo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cocojambo.Migrations
{
    [DbContext(typeof(MvvmContext))]
    [Migration("20241212173257_sss")]
    partial class sss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cocojambo.Models.Entities.CarEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("GenerationId")
                        .HasColumnType("int")
                        .HasColumnName("GenerationID");

                    b.Property<int?>("MarkId")
                        .HasColumnType("int")
                        .HasColumnName("MarkID");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("ModelID");

                    b.Property<int?>("PacageId")
                        .HasColumnType("int")
                        .HasColumnName("PacageID");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CarEntit__3214EC07C6B45D39");

                    b.HasIndex("GenerationId");

                    b.HasIndex("MarkId");

                    b.HasIndex("ModelId");

                    b.HasIndex("PacageId");

                    b.ToTable("CarEntities");
                });

            modelBuilder.Entity("Cocojambo.Models.Entities.GenerationEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("NameGeneration")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.HasKey("Id")
                        .HasName("PK__Generati__3214EC07F4B7FCEF");

                    b.ToTable("GenerationEntities");
                });

            modelBuilder.Entity("Cocojambo.Models.Entities.MarkEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("NameMark")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.HasKey("Id")
                        .HasName("PK__MarkEnti__3214EC076EEB34C5");

                    b.ToTable("MarkEntities");
                });

            modelBuilder.Entity("Cocojambo.Models.Entities.ModelEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("NameModelCar")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.HasKey("Id")
                        .HasName("PK__ModelEnt__3214EC0751E504B4");

                    b.ToTable("ModelEntities");
                });

            modelBuilder.Entity("Cocojambo.Models.Entities.PacageEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CallColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CallType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DriveType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EnginePower")
                        .HasColumnType("int");

                    b.Property<string>("EngineVolume")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Kpptype")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("KPPType");

                    b.Property<string>("NamePacage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Rudder")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__PacageEn__3214EC0791A6B555");

                    b.ToTable("PacageEntities");
                });

            modelBuilder.Entity("Cocojambo.Models.Entities.CarEntity", b =>
                {
                    b.HasOne("Cocojambo.Models.Entities.GenerationEntity", "Generation")
                        .WithMany("CarEntities")
                        .HasForeignKey("GenerationId")
                        .HasConstraintName("FK__CarEntiti__Gener__412EB0B6");

                    b.HasOne("Cocojambo.Models.Entities.MarkEntity", "Mark")
                        .WithMany("CarEntities")
                        .HasForeignKey("MarkId")
                        .HasConstraintName("FK__CarEntiti__MarkI__3F466844");

                    b.HasOne("Cocojambo.Models.Entities.ModelEntity", "Model")
                        .WithMany("CarEntities")
                        .HasForeignKey("ModelId")
                        .HasConstraintName("FK__CarEntiti__Model__403A8C7D");

                    b.HasOne("Cocojambo.Models.Entities.PacageEntity", "Pacage")
                        .WithMany("CarEntities")
                        .HasForeignKey("PacageId")
                        .HasConstraintName("FK__CarEntiti__Pacag__4222D4EF");

                    b.Navigation("Generation");

                    b.Navigation("Mark");

                    b.Navigation("Model");

                    b.Navigation("Pacage");
                });

            modelBuilder.Entity("Cocojambo.Models.Entities.GenerationEntity", b =>
                {
                    b.Navigation("CarEntities");
                });

            modelBuilder.Entity("Cocojambo.Models.Entities.MarkEntity", b =>
                {
                    b.Navigation("CarEntities");
                });

            modelBuilder.Entity("Cocojambo.Models.Entities.ModelEntity", b =>
                {
                    b.Navigation("CarEntities");
                });

            modelBuilder.Entity("Cocojambo.Models.Entities.PacageEntity", b =>
                {
                    b.Navigation("CarEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
