// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mvvm.Models;

#nullable disable

namespace Mvvm.Migrations
{
    [DbContext(typeof(MvvmContext))]
    [Migration("20241211190408_salfetka")]
    partial class salfetka
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mvvm.Models.Entities.CarEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("GenerationId")
                        .HasColumnType("int")
                        .HasColumnName("GenerationID");

                    b.Property<int?>("MarkId")
                        .HasColumnType("int")
                        .HasColumnName("MarkID");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("ModelID");

                    b.Property<int?>("PacageId")
                        .HasColumnType("int")
                        .HasColumnName("PacageID");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CarEntit__3214EC07EBDBAC32");

                    b.HasIndex("GenerationId");

                    b.HasIndex("MarkId");

                    b.HasIndex("ModelId");

                    b.HasIndex("PacageId");

                    b.ToTable("CarEntity", (string)null);
                });

            modelBuilder.Entity("Mvvm.Models.Entities.GenerationEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("NameGeneration")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.HasKey("Id")
                        .HasName("PK__Generati__3214EC07D8791B49");

                    b.ToTable("GenerationEntity", (string)null);
                });

            modelBuilder.Entity("Mvvm.Models.Entities.Login", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Logins")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("pass");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("roles");

                    b.HasKey("Id")
                        .HasName("PK__logins__3214EC27C4277C0C");

                    b.ToTable("logins", (string)null);
                });

            modelBuilder.Entity("Mvvm.Models.Entities.MarkEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("NameModelCar")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.HasKey("Id")
                        .HasName("PK__MarkEnti__3214EC0788753415");

                    b.ToTable("MarkEntity", (string)null);
                });

            modelBuilder.Entity("Mvvm.Models.Entities.ModelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("НазваниеМодели")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)")
                        .HasColumnName("Название_модели");

                    b.HasKey("Id")
                        .HasName("PK__ModelEnt__3214EC07949F7CCA");

                    b.ToTable("ModelEntity", (string)null);
                });

            modelBuilder.Entity("Mvvm.Models.Entities.PacageEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CallColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CallType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DriveType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EnginePower")
                        .HasColumnType("int");

                    b.Property<string>("EngineVolume")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Kpptype")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("KPPType");

                    b.Property<string>("NamePacage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Rudder")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__PacageEn__3214EC07037E7C4B");

                    b.ToTable("PacageEntity", (string)null);
                });

            modelBuilder.Entity("Mvvm.Models.Entities.CarEntity", b =>
                {
                    b.HasOne("Mvvm.Models.Entities.GenerationEntity", "Generation")
                        .WithMany("CarEntities")
                        .HasForeignKey("GenerationId")
                        .HasConstraintName("FK__CarEntity__Gener__6D0D32F4");

                    b.HasOne("Mvvm.Models.Entities.MarkEntity", "Mark")
                        .WithMany("CarEntities")
                        .HasForeignKey("MarkId")
                        .HasConstraintName("FK__CarEntity__MarkI__6B24EA82");

                    b.HasOne("Mvvm.Models.Entities.ModelEntity", "Model")
                        .WithMany("CarEntities")
                        .HasForeignKey("ModelId")
                        .HasConstraintName("FK__CarEntity__Model__6C190EBB");

                    b.HasOne("Mvvm.Models.Entities.PacageEntity", "Pacage")
                        .WithMany("CarEntities")
                        .HasForeignKey("PacageId")
                        .HasConstraintName("FK__CarEntity__Pacag__6E01572D");

                    b.Navigation("Generation");

                    b.Navigation("Mark");

                    b.Navigation("Model");

                    b.Navigation("Pacage");
                });

            modelBuilder.Entity("Mvvm.Models.Entities.GenerationEntity", b =>
                {
                    b.Navigation("CarEntities");
                });

            modelBuilder.Entity("Mvvm.Models.Entities.MarkEntity", b =>
                {
                    b.Navigation("CarEntities");
                });

            modelBuilder.Entity("Mvvm.Models.Entities.ModelEntity", b =>
                {
                    b.Navigation("CarEntities");
                });

            modelBuilder.Entity("Mvvm.Models.Entities.PacageEntity", b =>
                {
                    b.Navigation("CarEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
